# Azure pipelines for the mdclight client. It's separated for dev to fasten up the build time

# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

trigger:
  branches:
    exclude: [main, staging]

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_REGISTRY: mdclightdev.azurecr.io
  BRANCH_NAME: $[replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '-')]

steps:
  - task: Docker@2
    displayName: Login
    inputs:
      containerRegistry: 'mdc-light-acr-dev'
      command: 'login'
  - task: CmdLine@2
    displayName: PrintVersion
    inputs:
      script: |
        git describe --tags
  - task: CmdLine@2
    displayName: BuildWebserver
    inputs:
      script: |
        version=$(git describe --tags)
        docker run --privileged --rm tonistiigi/binfmt --install arm64
        docker run --privileged --rm tonistiigi/binfmt
        docker buildx create --use
        scripts/build/dockerBuildWebserver.sh $version
