# Azure pipelines for the mdclight

# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

trigger:
  branches:
    include: [main]

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_REGISTRY: mdclight.azurecr.io
  BRANCH_NAME: $[replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '-')]

steps:
  - task: Docker@2
    displayName: Login
    inputs:
      containerRegistry: 'mdc-light-acr'
      command: 'login'
  - task: CmdLine@2
    displayName: BuildBase
    inputs:
      script: | # Only build image if dockerfile has changed
        MATCH_COUNT=$(scripts/build/utils/countChangedFiles.sh "docker/mdclight-base.Dockerfile")

        echo "$MATCH_COUNT match(es) found."
        # if [[ $MATCH_COUNT -gt 0 ]]; then
        docker run --privileged --rm tonistiigi/binfmt --install arm64
        docker run --privileged --rm tonistiigi/binfmt
        docker buildx create --use
        scripts/build/dockerBuildMdclightBase.sh
        # fi
  - task: CmdLine@2
    displayName: BuildMtc
    inputs:
      script: | # Only build image if dockerfile has changed
        MATCH_COUNT=$(scripts/build/utils/countChangedFiles.sh "docker/mtconnect_arm64.dockerfile")

        echo "$MATCH_COUNT match(es) found."
        # if [[ $MATCH_COUNT -gt 0 ]]; then
          # docker run --privileged --rm tonistiigi/binfmt --install arm64
          # docker run --privileged --rm tonistiigi/binfmt
          # docker buildx create --use
          # scripts/build/dockerBuildMtc.sh

          # There is currently an issue with building the MTC image. Until that is fixed it's loaded from S3 to at least provide an images that can be used.
          wget -O mtconnect-prod_arm64_latest.tar.gz https://codestryke-artifacts.s3.eu-central-1.amazonaws.com/dmg-mdclight/images/q7z862htFYFQZHNJ7WEBtwpzdtYsNd24/mtconnect-prod_arm64_latest.tar.gz
          docker load -i mtconnect-prod_arm64_latest.tar.gz
          docker tag mdclightdev.azurecr.io/mtconnect-prod_arm64:latest ${DOCKER_REGISTRY}/mtconnect-prod_arm64:latest
          docker push ${DOCKER_REGISTRY}/mtconnect-prod_arm64:latest
        # fi
  - task: CmdLine@2
    displayName: BuildMdc
    inputs:
      script: |
        docker run --privileged --rm tonistiigi/binfmt --install arm64
        docker run --privileged --rm tonistiigi/binfmt
        docker buildx create --use
        scripts/build/dockerBuildMdclight.sh
  - task: CmdLine@2
    displayName: BuildWebserver
    inputs:
      script: |
        docker run --privileged --rm tonistiigi/binfmt --install arm64
        docker run --privileged --rm tonistiigi/binfmt
        docker buildx create --use
        scripts/build/dockerBuildWebserver.sh
