# Azure pipelines for the mdclight

# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines

trigger:
  branches:
    exclude: [main, staging]

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_REGISTRY: mdclightdev.azurecr.io
  BRANCH_NAME: $[replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '-')]

steps:
  - task: Docker@2
    displayName: Login
    inputs:
      containerRegistry: 'mdc-light-acr-dev'
      command: 'login'
  - task: CmdLine@2
    displayName: PrintVersion
    inputs:
      script: git describe --tags
  - task: CmdLine@2
    displayName: BuildMtc
    inputs:
      script: | # Only build image if dockerfile has changed
        MATCH_COUNT=$(scripts/build/utils/countChangedFiles.sh "_mdclight/mtc-config/prod")

        MATCH_COUNT=1 # Force build

        version=$(git describe --tags)

        echo "$MATCH_COUNT match(es) for filter '$PATH_FILTER' found."
        if [[ $MATCH_COUNT -gt 0 ]]; then
          docker run --privileged --rm tonistiigi/binfmt --install arm64
          docker run --privileged --rm tonistiigi/binfmt
          docker buildx create --use
          scripts/build/dockerBuildMtc.sh $version
        fi
