version: "3.8"

services:
  mtc-agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    ports:
      - 5000:5000
    restart: unless-stopped
