export default [
  { name: 'IN', type: 'measurement', address: 'in' },
  { name: 'P', type: 'measurement', address: 'p' },
  { name: 'Q', type: 'measurement', address: 'q' },
  { name: 'S', type: 'measurement', address: 's' },
  { name: 'PF', type: 'measurement', address: 'pf' },
  { name: 'Ea+', type: 'meter', address: 'ea-pos-total' },
  { name: 'Ea-', type: 'meter', address: 'ea-neg-total' },
  { name: 'Er+', type: 'meter', address: 'er-pos-total' },
  { name: 'Er-', type: 'meter', address: 'er-neg-total' },
  { name: 'T1 Ea+', type: 'meter', address: 't1-ea-pos' },
  { name: 'T1 Ea-', type: 'meter', address: 't1-ea-neg' },
  { name: 'T1 Er+', type: 'meter', address: 't1-er-pos' },
  { name: 'T1 Er-', type: 'meter', address: 't1-er-neg' },
  { name: 'T1 Es', type: 'meter', address: 't1-es' },
  { name: 'T1 Er', type: 'meter', address: 't1-er' },
  { name: 'T1 Runtime', type: 'meter', address: 't1-runtime' },
  { name: 'T2 Ea+', type: 'meter', address: 't2-ea-pos' },
  { name: 'T2 Ea-', type: 'meter', address: 't2-ea-neg' },
  { name: 'T2 Er+', type: 'meter', address: 't2-er-pos' },
  { name: 'T2 Er-', type: 'meter', address: 't2-er-neg' },
  { name: 'T2 Es', type: 'meter', address: 't2-es' },
  { name: 'T2 Er', type: 'meter', address: 't2-er' },
  { name: 'T2 Runtime', type: 'meter', address: 't2-runtime' },
  { name: 'T3 Ea+', type: 'meter', address: 't3-ea-pos' },
  { name: 'T3 Ea-', type: 'meter', address: 't3-ea-neg' },
  { name: 'T3 Er+', type: 'meter', address: 't3-er-pos' },
  { name: 'T3 Er-', type: 'meter', address: 't3-er-neg' },
  { name: 'T3 Es', type: 'meter', address: 't3-es' },
  { name: 'T3 Er', type: 'meter', address: 't3-er' },
  { name: 'T3 Runtime', type: 'meter', address: 't3-runtime' },
  { name: 'T4 Ea+', type: 'meter', address: 't4-ea-pos' },
  { name: 'T4 Ea-', type: 'meter', address: 't4-ea-neg' },
  { name: 'T4 Er+', type: 'meter', address: 't4-er-pos' },
  { name: 'T4 Er-', type: 'meter', address: 't4-er-neg' },
  { name: 'T4 Es', type: 'meter', address: 't4-es' },
  { name: 'T4 Er', type: 'meter', address: 't4-er' },
  { name: 'T4 Runtime', type: 'meter', address: 't4-runtime' },
  {
    name: 'Tariff',
    type: 'device',
    address: 'tariff-number',
    mandatory: true
  },
  { name: 'Firmware Version', type: 'device', address: 'fw' },
  { name: 'Hardware Version', type: 'device', address: 'hw' },
  { name: 'Serial Number', type: 'device', address: 'serial-number' },
  { name: 'MAC Address', type: 'device', address: 'mac' },
  { name: 'Article Number', type: 'device', address: 'article-number' }
];
