version: '3.3'
services:
  webserver:
    build: 
      context: ..
      dockerfile: docker/mdcwebserver_x86.Dockerfile
    restart: always
    ports:
      - '443:443'
    volumes:
      - type: bind
        source: ../_mdclight/local/ssl_private.key
        target: /etc/ssl/private/private.key
      - type: bind
        source: ../_mdclight/local/ssl.crt
        target: /etc/ssl/certs/ssl.crt
    depends_on:
      - mdclight
    labels:
      autoheal: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'https://localhost', '--insecure']
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
  mdclight:
    privileged: true
    build: 
      context: ..
      dockerfile: docker/mdclight_local.Dockerfile
    #restart: always
    volumes:
      - type: bind
        source: ../_mdclight/local/config
        target: /mdclight
      - type: bind
        source: ../_mdclight/local/logs
        target: /mdclight/logs
      # - type: bind
      #   source: $HOST/proc
      #   target: /proc
      - type: bind
        source: ../_mdclight/local/fakeSSH
        target: /root/.ssh/nmcli
    environment:
      - PORT=80
      - LOG_LEVEL=debug
    ports:
      - '4840:4840'
    extra_hosts:
    # TODO: Umbiegen auf fake ssh container
      - 'host.docker.internal:host-gateway'
    labels:
      autoheal: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/api/v1/healthcheck']
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
  # # mtconnect-agent:
  #   image: registry.gitlab.com/codestryke-tech/dmg-mori/mdc-light/mtconnect-prod_arm64:latest
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: $HOST/etc/MDCLight/mtc_config
  #       target: /agentConfiguration
  #   depends_on:
  #     - mdclight
  #   ports:
  #     - '15404:5000'
  #   labels:
  #     autoheal: true
  #   healthcheck:
  #     test: ['CMD', 'curl', '-f', 'http://localhost:5000/current']
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-size: '50m'
 
