version: '3.3'
services:
  mdclight:
    privileged: true
    build:
      context: ..
      dockerfile: docker/mdclight_local.Dockerfile
      args:
        MDC_LIGHT_RUNTIME_VERSION: ${MDC_LIGHT_RUNTIME_VERSION}
    #restart: always
    volumes:
      - type: bind
        source: ../mdclight
        target: /mdclight
      - type: bind
        source: ../mdclight/sys
        target: /sys
      # - type: bind
      #   source: $HOST/proc
      #   target: /proc
    environment:
      - PORT=80
      - LOG_LEVEL=debug
    ports:
      - '4840:4840'
      - '8083:80'
    extra_hosts:
      # TODO: Umbiegen auf fake ssh container
      - 'host.docker.internal:host-gateway'
    labels:
      autoheal: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/api/v1/healthcheck']
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
