version: '3.3'
services:
  webserver:
    image: registry.gitlab.com/codestryke-tech/dmg-mori/mdc-light/mdc-web-server:latest
    restart: always
    ports:
      - '80:8080'
    volumes:
      - type: bind
        source: $HOST/etc/MDCLight/config/ssl_private.key
        target: /etc/ssl/private/private.key
      - type: bind
        source: $HOST/etc/MDCLight/config/ssl.crt
        target: /etc/ssl/certs/ssl.crt
    depends_on:
      - mdclight
  mdclight:
    privileged: true
    image: registry.gitlab.com/codestryke-tech/dmg-mori/mdc-light/mdclight:latest
    restart: always
    volumes:
      - type: bind
        source: $HOST/etc/MDCLight/config
        target: /mdclight/config
      - type: bind
        source: $HOST/etc/MDCLight/logs
        target: /mdclight/logs
      - type: bind
        source: $HOST/proc
        target: /proc
      - type: bind
        source: $HOST/sys
        target: /sys
    environment:
      - PORT=80
    ports:
      - '4840:4840'
  mtconnect-agent:
    image: registry.gitlab.com/codestryke-tech/dmg-mori/mdc-light/mtconnect-prod_arm64:latest
    restart: always
    volumes:
      - type: bind
        source: $HOST/etc/MDCLight/mtc_config
        target: /agentConfiguration
    depends_on:
      - mdclight
    ports:
      - '5000:5000'
