version: '3.3'
services:
  mdclight:
    privileged: true
    image: registry.gitlab.com/codestryke-tech/dmg-mori/mdc-light/mdclight-prod_arm64:latest
    restart: always
    volumes:
      - type: bind
        source: $HOST/etc/MDCLight/config
        target: /mdclight/config
      - type: bind
        source: $HOST/etc/MDCLight/logs
        target: /mdclight/logs
      - type: bind
        source: $HOST/proc
        target: /proc
      - type: bind
        source: $HOST/sys
        target: /sys
  mtconnect-agent:
    image: registry.gitlab.com/codestryke-tech/dmg-mori/mdc-light/mtconnect-prod_arm64:latest
    restart: always
    volumes:
      - type: bind
        source: $HOST/etc/MDCLight/mtc_config
        target: /agentConfiguration
    ports:
      - '5000:5000'
