version: '3.3'
services:
  webserver:
    image: ${DOCKER_REGISTRY}/mdc-web-server:${DOCKER_WEBSERVER_TAG}
    restart: always
    ports:
      - '443:443'
    volumes:
      - type: bind
        source: /etc/MDCLight/config/ssl_private.key
        target: /etc/ssl/private/private.key
      - type: bind
        source: /etc/MDCLight/config/ssl.crt
        target: /etc/ssl/certs/ssl.crt
    depends_on:
      - mdclight
    labels:
      autoheal: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'https://localhost', '--insecure']
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
  mdclight:
    privileged: true
    image: ${DOCKER_REGISTRY}/mdclight:${DOCKER_MDC_TAG}
    restart: always
    volumes:
      - type: bind
        source: /etc/MDCLight/config
        target: /mdclight/config
      - type: bind
        source: /etc/MDCLight/logs
        target: /mdclight/logs
      - type: bind
        source: /etc/mdcflex-os-release
        target: /etc/mdcflex-os-release
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys
        target: /sys
      - type: bind
        source: /home/mdclite/.ssh/nmcli
        target: /root/.ssh/nmcli
      - type: bind
        read_only: true
        source: /var/log
        target: /host/log/system
      - type: bind
        read_only: true
        source: /var/lib/docker/containers
        target: /host/log/docker
      - type: bind
        read_only: true
        source: /etc/timezone
        target: /etc/timezone
    environment:
      - PORT=80
      - LOG_LEVEL=debug
    ports:
      - '4840:4840'
      - '7878:7878'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      autoheal: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/api/v1/healthcheck']
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
  mtconnect-agent:
    image: ${DOCKER_REGISTRY}/mtconnect-prod_arm64:${DOCKER_MTC_TAG}
    restart: always
    volumes:
      - type: bind
        source: /etc/MDCLight/mtc_config
        target: /agentConfiguration
    depends_on:
      - mdclight
    ports:
      - '15404:5000'
    labels:
      autoheal: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/current']
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
