/**
 * INFO: Addresses and endpoints are defined at links below.
 * @see https://jira.app.dmgmori.com/browse/DIGMDCLGHT-295
 * @see http://www.empro.phoenixcontact.com/api#ex-x83q8
 */
export const EMPRO_GET_ENDPOINTS: { [key: string]: string } = {
  f: '/api/v1/measurements/f',
  U1: '/api/v1/measurements/u1',
  U2: '/api/v1/measurements/u2',
  U3: '/api/v1/measurements/u3',
  U12: '/api/v1/measurements/u12',
  U23: '/api/v1/measurements/u23',
  U31: '/api/v1/measurements/u31',
  I1: '/api/v1/measurements/i1',
  I2: '/api/v1/measurements/i2',
  I3: '/api/v1/measurements/i3',
  IN: '/api/v1/measurements/in',
  P1: '/api/v1/measurements/p1',
  P2: '/api/v1/measurements/p2',
  P3: '/api/v1/measurements/p3',
  Q1: '/api/v1/measurements/q1',
  Q2: '/api/v1/measurements/q2',
  Q3: '/api/v1/measurements/q3',
  S1: '/api/v1/measurements/s1',
  S2: '/api/v1/measurements/s2',
  S3: '/api/v1/measurements/s3',
  PF1: '/api/v1/measurements/pf1',
  PF2: '/api/v1/measurements/pf2',
  PF3: '/api/v1/measurements/pf3',
  P: '/api/v1/measurements/p',
  Q: '/api/v1/measurements/q',
  S: '/api/v1/measurements/s',
  PF: '/api/v1/measurements/pf',
  'Ea+ Total': '/api/v1/meters/ea-pos-total',
  'Ea- Total': '/api/v1/meters/ea-neg-total',
  'Er+ Total': '/api/v1/meters/er-pos-total',
  'Er- Total': '/api/v1/meters/er-neg-total',
  'Es Total': '/api/v1/meters/es-total',
  'Er Total': '/api/v1/meters/er-total',
  'Ea+': '/api/v1/meters/ea-pos',
  'Ea-': '/api/v1/meters/ea-neg',
  'Er+': '/api/v1/meters/er-pos',
  'Er-': '/api/v1/meters/er-neg',
  Es: '/api/v1/meters/es',
  Er: '/api/v1/meters/er',
  'E Runtime': '/api/v1/meters/e-runtime',
  'T1 Ea+': '/api/v1/meters/t1-ea-pos',
  'T1 Ea-': '/api/v1/meters/t1-ea-neg',
  'T1 Er+': '/api/v1/meters/t1-er-pos',
  'T1 Er-': '/api/v1/meters/t1-er-neg',
  'T1 Es': '/api/v1/meters/t1-es',
  'T1 Er': '/api/v1/meters/t1-er',
  'T1 E Runtime': '/api/v1/meters/t1-runtime',
  'T2 Ea+': '/api/v1/meters/t2-ea-pos',
  'T2 Ea-': '/api/v1/meters/t2-ea-neg',
  'T2 Er+': '/api/v1/meters/t2-er-pos',
  'T2 Er-': '/api/v1/meters/t2-er-neg',
  'T2 Es': '/api/v1/meters/t2-es',
  'T2 Er': '/api/v1/meters/t2-er',
  'T2 E Runtime': '/api/v1/meters/t2-runtime',
  'T3 Ea+': '/api/v1/meters/t3-ea-pos',
  'T3 Ea-': '/api/v1/meters/t3-ea-neg',
  'T3 Er+': '/api/v1/meters/t3-er-pos',
  'T3 Er-': '/api/v1/meters/t3-er-neg',
  'T3 Es': '/api/v1/meters/t3-es',
  'T3 Er': '/api/v1/meters/t3-er',
  'T3 E Runtime': '/api/v1/meters/t3-runtime',
  'T4 Ea+': '/api/v1/meters/t4-ea-pos',
  'T4 Ea-': '/api/v1/meters/t4-ea-neg',
  'T4 Er+': '/api/v1/meters/t4-er-pos',
  'T4 Er-': '/api/v1/meters/t4-er-neg',
  'T4 Es': '/api/v1/meters/t4-es',
  'T4 Er': '/api/v1/meters/t4-er',
  'T4 E Runtime': '/api/v1/meters/t4-runtime',
  Device: '/api/v1/information/name',
  'Hardware Version': '/api/v1/information/hw',
  'Firmware Version': '/api/v1/information/fw',
  'Serial Number': '/api/v1/information/serial-number',
  'Device Label': '/api/v1/information/label',
  'Metering Point': '/api/v1/information/metering-point',
  UUID: '/api/v1/information/uuid',
  'MAC Address': '/api/v1/information/mac',
  'Article Number': '/api/v1/information/article-number',
  'Vendor Name': '/api/v1/information/vendor',
  'Vendor Homepage': '/api/v1/information/vendor-url',
  'Production Date': '/api/v1/information/production-date',
  'Opening Hours': '/api/v1/information/operating-hours',
  'Tariff Number': '/api/v1/measurement-system-control/tariff-number'
};
